meta_product_name: "The Healthy Hair Hub"
meta_title: "The Healthy Hair Hub - A community for styling Afro-Caribbean hair"
meta_description: "We share tips and tricks to help you learn to take care of your hair at home"
meta_image: "happyhairhub.png" # should exist in `app/assets/images/`
