meta_product_name: "The Healthy Hair Hub"
meta_title: "The Healthy Hair Hub - Your online community"
meta_description: "For all your afro hair related needs, queries and questions"
meta_image: "afro.jpg" # should exist in `app/assets/images/`
