meta_product_name: "The Healthy Hair Hub"
meta_title: "The Healthy Hair Hub - The Most Reliable Tool Is You"
meta_description: "The number 1 resource for home haircare for Afro-Textured hair."
meta_image: "app/assets/images/tattoos.jpg" # should exist in `app/assets/images/`
twitter_account: ""
